[project]
name = "is-it-a-bird"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ddgs",
    "fastai",
    "icrawler",
    "datasets"
]
